### ISSUE TITLE
Dear Mr Strommer

### ISSUE THREAD

**Issue by SpodoY** [mstrommer/ALDA_Exercise5v12022#1]
# As per usual, the meme
![6jshod](https://user-images.githubusercontent.com/72346498/173918627-48de87da-daf9-4aa5-809c-95327d68dbaf.jpg)

**Comment by megamxl** [comment]
Urgent. Pls fix. Cant do any work at the moment 👹

**Comment by meli0904** [comment]
:D

**Comment by mstrommer** [comment]
Working intensively on it ;) Expect it until Monday ;)

**Comment by mstrommer** [comment]
https://github.com/mstrommer/ALDA_Exercise6v12022.git

The Repo is ready to use. GithubClassroom Assignment link and problem description will follow. But I guess you know what's to be done ;)
